pipeline {
    agent any
    tools {nodejs "node1415"}

    environment {
        DOCKER_IMAGE = "vuejs-practice"
        TAG = "${BUILD_NUMBER}"
        DOCKER_IMAGENAME = "${DOCKER_IMAGE}:${TAG}"
        NODEPORT = "11110"
        NAMESPACE = "myproject"
    }

    stages {
        // stage('git checkout') {
        //     steps {
        //         checkout changelog: false, poll: false, scm: [$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/choisungwook/vuetify-practice.git']]]
        //     }
        // }
        stage('yarn install&build'){
            steps{
                sh 'yarn install'
                sh 'yarn build'
            }
        }
        stage('docker build&push'){
            steps{
                sh 'cp cicd/* ./'
                withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                    script{
                        sh 'docker build -t ${dockerID}/${DOCKER_IMAGENAME} .'
                        withCredentials([usernamePassword(credentialsId: 'docker', passwordVariable: 'dockerpassword', usernameVariable: 'dockeruser')]) {
                            sh 'docker login -u ${dockeruser} -p ${dockerpassword}'
                            sh 'docker push ${dockerID}/${DOCKER_IMAGENAME}'
                        }
                    }
                }
            }
        }
        stage('deploy'){
            steps{
                withCredentials([string(credentialsId: 'dockerID', variable: 'dockerID')]) {
                    sh 'sed -i "s/__IMAGE_NAME__/${dockerID}\\/${DOCKER_IMAGENAME}/g" kubernetes-deploy.yaml'
                    sh 'sed -i "s/__NAMESPACE__/${NAMESPACE}/g" kubernetes-deploy.yaml'
                    sh 'sed -i "s/__NODEPORT__/${NODEPORT}/g" kubernetes-deploy.yaml'
                    sh 'kubectl apply -f kubernetes-deploy.yaml'
                }
            }
        }
    }
}
